theme: jekyll-theme-minimal
title: Akira Endo, MD PhD
description: Infectious disease modeller at London School of Hygiene & Tropical Medicine. <br/> <a href="https://orcid.org/0000-0001-6377-7296", target="_blank"> [ORCID] </a> <a href="https://scholar.google.co.jp/citations?user=M-fArWcAAAAJ", target="_blank"> [Google Scholar] </a> <a href="http://twitter.com/_akiraendo/", target="_blank"> [Twitter] </a> <a href="mailto:akira.endo@lshtm.ac.uk"> [Mail] </a> <br/><br/>
logo: /img/ae.jpg
