theme: jekyll-theme-minimal
title: Akira Endo, MD
description: Infectious disease modeller at London School of Hygiene & Tropical Medicine. <a href="https://orcid.org/0000-0001-6377-7296">ORCID<\a> [Google Scholar] [Twitter](http://twitter.com/_akiraendo/)
logo: /img/ae.jpg
