theme: jekyll-theme-minimal
title: Akira Endo, MD
description: Infectious disease modeller at London School of Hygiene & Tropical Medicine."<a href=""https://orcid.org/0000-0001-6377-7296">ORCID: 0000-0001-6377-7296"</a>" 
logo: /img/ae.jpg
